# Generated by Django 5.2.12 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_spellpatchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellpatchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
