# Generated by Django 5.2.12 on 2026-05-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_alter_spellpatchhistory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellScroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_id', models.IntegerField(help_text='Game-DB spell id (spells_new.id)', unique=True)),
                ('spell_name', models.CharField(max_length=64)),
                ('scroll_item_id', models.IntegerField()),
                ('scroll_item_name', models.CharField(max_length=64)),
                ('scroll_price', models.IntegerField(default=0)),
                ('scroll_rate', models.IntegerField(default=1, help_text='Merchant price modifier from the game DB')),
                ('icon', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'spell_scroll',
                'ordering': ['spell_name'],
            },
        ),
        migrations.CreateModel(
            name='SpellVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.IntegerField()),
                ('merchant_name', models.CharField(max_length=64)),
                ('zone_short_name', models.CharField(max_length=32)),
                ('zone_long_name', models.CharField(max_length=64)),
                ('zone_id', models.IntegerField()),
                ('zone_expansion', models.IntegerField(default=0, help_text="Expansion the vendor's zone was introduced in")),
                ('scroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='spells.spellscroll')),
            ],
            options={
                'db_table': 'spell_vendor',
                'unique_together': {('scroll', 'merchant_id')},
            },
        ),
    ]
