# Generated by Django 5.2.12 on 2026-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_spell_scroll_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='spellexpansion',
            name='spell_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized name for display (game DB is read-only).', max_length=64),
        ),
    ]
