from django.db import models


class Zone(models.Model):
    """
    This model maps to the zone table in the database.
    """

    def __str__(self):
        return str(self.short_name)

    id = models.AutoField(primary_key=True)
    zone_id_number = models.IntegerField(null=False, default=0, db_column="zoneidnumber")
    version = models.PositiveSmallIntegerField(null=False, default=0)
    short_name = models.CharField(max_length=32, null=True, default=None)
    long_name = models.TextField(null=False)
    min_status = models.PositiveSmallIntegerField(null=False, default=0)
    map_file_name = models.CharField(max_length=100, null=True, default=None)
    note = models.CharField(max_length=200, null=True, default=None)
    min_expansion = models.SmallIntegerField(null=False, default=-1)
    max_expansion = models.SmallIntegerField(null=False, default=-1)
    content_flags = models.CharField(max_length=100, null=True, default=None)
    content_flags_disabled = models.CharField(max_length=100, null=True, default=None)
    expansion = models.SmallIntegerField(null=False, default=0)
    file_name = models.CharField(max_length=16, null=True, default=None)
    safe_x = models.FloatField(null=False, default=0.0)
    safe_y = models.FloatField(null=False, default=0.0)
    safe_z = models.FloatField(null=False, default=0.0)
    safe_heading = models.FloatField(null=False, default=0.0)
    graveyard_id = models.FloatField(null=False, default=0.0)
    min_level = models.PositiveSmallIntegerField(null=False, default=0)
    max_level = models.PositiveSmallIntegerField(null=False, default=255)
    timezone = models.IntegerField(null=False, default=0)
    max_clients = models.IntegerField(null=False, default=0, db_column="maxclients")
    ruleset = models.PositiveIntegerField(null=False, default=0)
    underworld = models.FloatField(null=False, default=0)
    min_clip = models.FloatField(null=False, default=450, db_column="minclip")
    max_clip = models.FloatField(null=False, default=450, db_column="maxclip")
    fog_minclip = models.FloatField(null=False, default=450)
    fog_maxclip = models.FloatField(null=False, default=450)
    fog_blue = models.PositiveSmallIntegerField(null=False, default=0)
    fog_red = models.PositiveSmallIntegerField(null=False, default=0)
    fog_green = models.PositiveSmallIntegerField(null=False, default=0)
    sky = models.PositiveSmallIntegerField(null=False, default=1)
    ztype = models.PositiveSmallIntegerField(null=False, default=1)
    zone_exp_multiplier = models.DecimalField(null=False, default=0, max_digits=6, decimal_places=2)
    walkspeed = models.FloatField(null=False, default=0.4)
    time_type = models.PositiveSmallIntegerField(null=False, default=2)
    fog_red1 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_green1 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_blue1 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_minclip1 = models.FloatField(null=False, default=450)
    fog_maxclip1 = models.FloatField(null=False, default=450)
    fog_red2 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_green2 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_blue2 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_minclip2 = models.FloatField(null=False, default=450)
    fog_maxclip2 = models.FloatField(null=False, default=450)
    fog_red3 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_green3 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_blue3 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_minclip3 = models.FloatField(null=False, default=450)
    fog_maxclip3 = models.FloatField(null=False, default=450)
    fog_red4 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_green4 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_blue4 = models.PositiveSmallIntegerField(null=False, default=0)
    fog_minclip4 = models.FloatField(null=False, default=450)
    fog_maxclip4 = models.FloatField(null=False, default=450)
    fog_density = models.FloatField(null=False, default=0)
    flag_needed = models.CharField(max_length=128, null=False, default='')
    can_bind = models.SmallIntegerField(null=False, default=1, db_column="canbind")
    can_combat = models.SmallIntegerField(null=False, default=1, db_column="cancombat")
    can_levitate = models.SmallIntegerField(null=False, default=1, db_column="canlevitate")
    cast_outdoor = models.SmallIntegerField(null=False, default=1, db_column="castoutdoor")
    hotzone = models.PositiveSmallIntegerField(null=False, default=0)
    insttype = models.PositiveSmallIntegerField(null=False, default=0)
    shutdowndelay = models.BigIntegerField(null=False, default=5000)
    peqzone = models.SmallIntegerField(null=False, default=1)
    bypass_expansion_check = models.SmallIntegerField(null=False, default=0)
    suspendbuffs = models.PositiveSmallIntegerField(null=False, default=0)
    rain_chance1 = models.IntegerField(null=False, default=0)
    rain_chance2 = models.IntegerField(null=False, default=0)
    rain_chance3 = models.IntegerField(null=False, default=0)
    rain_chance4 = models.IntegerField(null=False, default=0)
    rain_duration1 = models.IntegerField(null=False, default=0)
    rain_duration2 = models.IntegerField(null=False, default=0)
    rain_duration3 = models.IntegerField(null=False, default=0)
    rain_duration4 = models.IntegerField(null=False, default=0)
    snow_chance1 = models.IntegerField(null=False, default=0)
    snow_chance2 = models.IntegerField(null=False, default=0)
    snow_chance3 = models.IntegerField(null=False, default=0)
    snow_chance4 = models.IntegerField(null=False, default=0)
    snow_duration1 = models.IntegerField(null=False, default=0)
    snow_duration2 = models.IntegerField(null=False, default=0)
    snow_duration3 = models.IntegerField(null=False, default=0)
    snow_duration4 = models.IntegerField(null=False, default=0)
    gravity = models.FloatField(null=False, default=0.4)
    zone_type = models.IntegerField(null=False, default=0, db_column="type")
    skylock = models.SmallIntegerField(null=False, default=0)
    fast_regen_hp = models.IntegerField(null=False, default=180)
    fast_regen_mana = models.IntegerField(null=False, default=180)
    fast_regen_endurance = models.IntegerField(null=False, default=180)
    npc_max_aggro_dist = models.IntegerField(null=False, default=600)
    client_update_range = models.IntegerField(null=False, default=600)
    underworld_teleport_index = models.IntegerField(null=False, default=0)
    lava_damage = models.IntegerField(null=True, default=50)
    min_lava_damage = models.IntegerField(null=False, default=10)
    idle_when_empty = models.PositiveSmallIntegerField(null=False, default=1)
    seconds_before_idle = models.PositiveIntegerField(null=False, default=60)
    shard_at_player_count = models.IntegerField(null=True, default=0)

    class Meta:
        db_table = "zone"
        managed = False


class ZonePoints(models.Model):
    """
    This model maps to the zone_points table in the database
    """

    def __str__(self):
        return str(self.id)

    id = models.AutoField(primary_key=True)
    zone = models.CharField(max_length=32, null=True, default=None)
    version = models.IntegerField(null=False, default=0)
    number = models.PositiveSmallIntegerField(null=False, default=1)
    y = models.FloatField(null=False, default=0)
    x = models.FloatField(null=False, default=0)
    z = models.FloatField(null=False, default=0)
    heading = models.FloatField(null=False, default=0)
    target_y = models.FloatField(null=False, default=0)
    target_x = models.FloatField(null=False, default=0)
    target_z = models.FloatField(null=False, default=0)
    target_heading = models.FloatField(null=False, default=0)
    zoneinst = models.PositiveSmallIntegerField(null=True, default=0)
    target_zone_id = models.PositiveIntegerField(null=False, default=0)
    target_instance = models.PositiveIntegerField(null=False, default=0)
    buffer = models.FloatField(null=True, default=0)
    client_version_mask = models.PositiveIntegerField(null=False, default=4294967295)
    min_expansion = models.SmallIntegerField(null=False, default=-1)
    max_expansion = models.SmallIntegerField(null=False, default=-1)
    content_flags = models.CharField(max_length=100, null=True, default=None)
    content_flags_disabled = models.CharField(max_length=100, null=True, default=None)
    is_virtual = models.SmallIntegerField(null=False, default=0)
    height = models.IntegerField(null=False, default=0)
    width = models.IntegerField(null=False, default=0)

    class Meta:
        db_table = "zone_points"
        managed = False
