# Generated by Django 5.2.12 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_faction_data_migration_and_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questfaction',
            options={'ordering': ['role', 'faction__name'], 'verbose_name': 'Quest Faction', 'verbose_name_plural': 'Quest Factions'},
        ),
        migrations.AlterField(
            model_name='faction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questissuereport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
