# Generated by Django 5.2.12 on 2026-05-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_alter_questfaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questfaction',
            name='quest_faction_id_idx',
        ),
    ]
