# Generated by Django 5.2.12 on 2026-05-16 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=50, unique=True)),
                ('account_password', models.TextField()),
                ('account_email', models.CharField(max_length=100)),
                ('source_loginserver', models.CharField(default=None, max_length=64, null=True)),
                ('last_ip_address', models.CharField(max_length=80)),
                ('last_login_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login Server Accounts',
                'db_table': 'login_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAccountOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_account_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_login_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'login_account_id')},
            },
        ),
        migrations.DeleteModel(
            name='LoginServerAccounts',
        ),
    ]
