# Generated by Django 5.2.12 on 2026-05-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginaccountownership'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serveradminregistration',
            table='login_server_admins',
        ),
        migrations.AlterModelTable(
            name='serverlisttype',
            table='login_server_list_types',
        ),
        migrations.AlterModelTable(
            name='worldserverregistration',
            table='login_world_servers',
        ),
    ]
