# Generated by Django 5.2.12 on 2026-05-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_serveradminregistration_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginaccountownership',
            table='accounts_loginaccountownership',
        ),
    ]
