# Generated by Django 5.2.12 on 2026-05-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_loginaccountownership_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginaccountownership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
