# Generated by Django 5.2.12 on 2026-05-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_loginaccountownership_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountIp',
            fields=[
                ('accid', models.IntegerField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('count', models.IntegerField(default=1)),
                ('lastused', models.DateTimeField()),
            ],
            options={
                'db_table': 'account_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpExemption',
            fields=[
                ('exemption_id', models.AutoField(primary_key=True, serialize=False)),
                ('exemption_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('exemption_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ip_exemptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('character_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('zone_id', models.IntegerField(blank=True, null=True)),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('event_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('event_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_data', models.TextField(blank=True, null=True)),
                ('etl_table_id', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'player_event_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuleValues',
            fields=[
                ('ruleset_id', models.IntegerField(default=0)),
                ('rule_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rule_value', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rule_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_account_id', models.IntegerField(unique=True)),
                ('is_trader', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_accountmetadata',
            },
        ),
    ]
