# Generated by Django 5.2.12 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0002_npcpatchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcpatchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
